import json

from services.ai_service import AIService


class ExecutiveBriefService:

    def __init__(self):
        self.ai = AIService()

    def generate(self, industry, articles):

        if not articles:
            return None

        # Sort by dashboard score and take top 15
        articles = sorted(
            articles,
            key=lambda x: x.dashboard_score or 0,
            reverse=True
        )[:15]

        article_text = ""

        for i, article in enumerate(articles, start=1):

            article_text += f"""
Article {i}

Headline:
{article.headline}

Summary:
{article.summary}

Company:
{article.company}

Country:
{article.country}

Category:
{article.category}

Priority:
{article.priority}

Business Impact:
{article.business_impact}

Recommended Action:
{article.recommended_action}

Dashboard Score:
{article.dashboard_score}

------------------------------------------
"""

        prompt = f"""
You are the Chief Strategy Officer of a Fortune 500 company.

Prepare today's Executive Intelligence Brief.

Industry:
{industry}

Below are the highest-priority intelligence reports generated by the Corporate Intelligence Team.

{article_text}

Your task is to produce ONE concise executive briefing.

Focus on:
- Biggest developments
- Emerging industry trends
- Competitive movements
- Risks
- Opportunities
- Strategic recommendations

Return ONLY valid JSON.

{{
    "headline":"One sentence describing today's biggest business development.",

    "summary":"150-200 word executive briefing summarizing the industry, explaining why these developments matter and what executives should know.",

    "key_trends":[
        "...",
        "...",
        "...",
        "...",
        "..."
    ],

    "recommended_actions":[
        "...",
        "...",
        "...",
        "...",
        "..."
    ]
}}
"""

        response = self.ai.chat(
            prompt,
            temperature=0.2,
            max_tokens=1200
        )

        try:

            response = (
                response
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

            return json.loads(response)

        except Exception as e:

            print("\n========== EXECUTIVE BRIEF PARSING ERROR ==========")
            print(e)
            print("\nRaw Response:\n")
            print(response)
            print("\n==================================================")

            return None